name: test

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  test-docker:
    name: Tests dj${{ matrix.dj }} / ${{ matrix.db }} / py${{ matrix.py }}

    runs-on: ubuntu-latest
    strategy:
      # all supported django version on lowest/highest supported python
      # see https://docs.djangoproject.com/en/4.1/faq/install/#what-python-version-can-i-use-with-django
      matrix:
        include:
          - { dj: "3.2", db: "sqlite", py: "3.6" }
          - { dj: "3.2", db: "sqlite", py: "3.10" }
          - { dj: "3.2", db: "postgres", py: "3.6" }
          - { dj: "3.2", db: "postgres", py: "3.10" }
          - { dj: "4.0", db: "sqlite", py: "3.8" }
          - { dj: "4.0", db: "sqlite", py: "3.10" }
          - { dj: "4.0", db: "postgres", py: "3.8" }
          - { dj: "4.0", db: "postgres", py: "3.10" }
          - { dj: "4.1", db: "sqlite", py: "3.8" }
          - { dj: "4.1", db: "sqlite", py: "3.11" }
          - { dj: "4.1", db: "postgres", py: "3.8" }
          - { dj: "4.1", db: "postgres", py: "3.11" }
      fail-fast: false

    env:
      TOOSIMPLEQ_DJ_VERSION: ${{ matrix.dj }}
      TOOSIMPLEQ_PY_VERSION: ${{ matrix.py }}
      TOOSIMPLEQ_TEST_DB: ${{ matrix.db }}

    steps:
      - uses: actions/checkout@v1

      - name: Lint with pre-commit
        uses: pre-commit/action@v2.0.2

      - name: Docker build
        run: docker compose build

      - name: Run tests
        run: docker compose run django test

  test-windows:
    name: Tests windows

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup postgres
        uses: ikalnytskyi/action-setup-postgres@v4

      - name: Install python deps
        run: pip install -r requirements-dev.txt -r requirements.txt

      - name: Run tests
        env:
          TOOSIMPLEQ_TEST_DB: postgres
          POSTGRES_PORT_WORKER: "5432"
        run: python manage.py test
